version: '3.6'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/data
    ports:
      - 9200:9200
    networks:
      esnet: {}

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      esnet: {}

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    container_name: logstash
    environment:
      - XPACK_MONITORING_ENABLED=true
      - XPACK_SECURITY_ENABLED=false
      - CONSUMER_KEY=${C_KEY}
      - CONSUMER_SECRET=${C_SEC}
      - OAUTH_TOKEN=${O_TOKEN}
      - OAUTH_TOKEN_SECRET=${O_TOKEN_SEC}
      - KEY_WORDS=${KEY_WORD}
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - ./components/pipeline/:/usr/share/logstash/pipeline/
    networks:
      esnet: {}

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
